---
name: "Generate go test cover report"

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  generate-reports:
    uses: heathcliff26/ci/.github/workflows/golang-testcover-report.yaml@482d6b77bbafaa616f7b29ee8086e998ceb2ab7c # main
    secrets: inherit
    permissions: {}
    with:
      coveralls: true
