---
name: "Generate go test cover report"

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  generate-reports:
    uses: heathcliff26/ci/.github/workflows/golang-testcover-report.yaml@main
    secrets: inherit
    permissions: {}

  coveralls:
    uses: heathcliff26/ci/.github/workflows/golang-unit-tests.yaml@main
    permissions:
      contents: read
    with:
      coveralls: true
