---
name: "Link Check"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  check-links:
    uses: heathcliff26/ci/.github/workflows/link-check.yaml@482d6b77bbafaa616f7b29ee8086e998ceb2ab7c # main
    secrets: inherit
    permissions: {}
    with:
      exclude-paths: "vendor"
